name: Send Letter

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  send-letter:
    runs-on: ubuntu-latest
    env:
      GMAIL_SMTP_SENDER: ${{ secrets.GMAIL_SMTP_SENDER }}
      GMAIL_SMTP_PASSWORD: ${{ secrets.GMAIL_SMTP_PASSWORD }}
      GMAIL_SMTP_SERVER: ${{ secrets.GMAIL_SMTP_SERVER }}
      GMAIL_SMTP_PORT: ${{ secrets.GMAIL_SMTP_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py
